# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Mage
        run: go run mage.go ConfigureAgent
      - name: Build
        run: mage -v Build
      - name: Test
        run: mage -v Test
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: mage -v Publish
        env:
          PORTER_REGISTRY: ghcr.io/getporter
